# Site settings
title: Kite SDK Development Guide
email: ddawson@cloudera.com
description: "Documentation for the Kite open source project on GitHub."
baseurl: ""
url: "http://cloudera.com"

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
  input: GFM
